version: 0.2

phases:
  install:
    #Si utiliza la imagen estándar de Ubuntu 2.0 o posterior, debe especificar las versiones del tiempo de ejecución.
    #Si especifica las versiones del tiempo de ejecución y utiliza una imagen que no sea la estándar de Ubuntu 2.0, se produce un error en la compilación.
    runtime-versions:
      nodejs: 18
    commands:
      - npm i -g yarn
      - npm i -g typescript
      - npm i -g @nestjs/cli

  build:
    commands:
      - yarn 
      - yarn prebuild
      - yarn build
      # - command
  post_build:
    commands:
      - yarn test
      - yarn test:e2e
      # - command

artifacts:
  files:
    - '**/*'